name: Update PA Voter Data

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC (8:00 AM EDT) daily
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'

    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 1.5.52
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev

    - name: Install R packages
      run: |
        install.packages(c('tidyverse', 'ggplot2', 'extrafont', 'here', 'openxlsx', 'scales', 'quarto'))
      shell: Rscript {0}
        
    - name: Download latest PA voter data
      run: |
        wget -O "2024 General Daily Mail Ballot Report.xlsx" "https://www.pavoterservices.pa.gov/2024%20General%20Daily%20Mail%20Ballot%20Report.xlsx"
        
    - name: Render Quarto document
      run: |
        quarto render PA_EV_Analysis.qmd --to html --output-dir docs
        
    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add docs/* "2024 General Daily Mail Ballot Report.xlsx"
        git commit -m "Update PA voter data $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push origin main